project_id = "horarium-classium-dev"
[auth]
site_url = "https://armenbadal.github.io/horarium-classium/"
additional_redirect_urls = ["http://localhost:5173", "http://127.0.0.1:5173", "http://127.0.0.1:5173/activate.html", "https://armenbadal.github.io/horarium-classium/activate.html"]
enable_signup = false
